"""companies_only_schema

Revision ID: 41d7b4e05d76
Revises: 
Create Date: 2025-09-18 12:36:58.552174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d7b4e05d76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=False),
    sa.Column('headquarters', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('total_funding_usd', sa.BigInteger(), nullable=False),
    sa.Column('arr_usd', sa.BigInteger(), nullable=False),
    sa.Column('valuation_usd', sa.BigInteger(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('top_investors', sa.Text(), nullable=False),
    sa.Column('product', sa.Text(), nullable=False),
    sa.Column('g2_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###